# Generated by Django 2.2.2 on 2019-06-13 21:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crafted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(choices=[('alchemy', 'alchemy'), ('blacksmithing', 'blacksmithing'), ('cooking', 'cooking'), ('enchanting', 'enchanting'), ('engineering', 'engineering'), ('leatherworking', 'leatherworking'), ('first_aid', 'first_aid'), ('skinning', 'skinning'), ('fishing', 'fishing'), ('herbalism', 'herbalism'), ('mining', 'mining'), ('other', 'other'), ('poisons', 'poisons')], default='alchemy', max_length=15)),
                ('step', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rarity', models.CharField(choices=[('junk', 'junk'), ('common', 'common'), ('uncommon', 'uncommon'), ('rare', 'rare'), ('epic', 'epic'), ('legendary', 'legendary')], default='common', max_length=10)),
                ('unique', models.BooleanField(default=False)),
                ('bop', models.BooleanField(default=False)),
                ('use', models.CharField(default='', max_length=250)),
                ('proper_name', models.CharField(blank=True, max_length=100)),
                ('required_level', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(60)])),
                ('description', models.CharField(default='', max_length=250)),
                ('stats', models.CharField(default='', max_length=350)),
                ('required_prof', models.CharField(blank=True, choices=[('alchemy', 'alchemy'), ('blacksmithing', 'blacksmithing'), ('cooking', 'cooking'), ('enchanting', 'enchanting'), ('engineering', 'engineering'), ('leatherworking', 'leatherworking'), ('first_aid', 'first_aid'), ('skinning', 'skinning'), ('fishing', 'fishing'), ('herbalism', 'herbalism'), ('mining', 'mining'), ('other', 'other'), ('poisons', 'poisons')], max_length=15)),
                ('required_prof_lvl', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(300)])),
                ('category', models.CharField(choices=[('alchemy', 'alchemy'), ('blacksmithing', 'blacksmithing'), ('cooking', 'cooking'), ('enchanting', 'enchanting'), ('engineering', 'engineering'), ('leatherworking', 'leatherworking'), ('first_aid', 'first_aid'), ('skinning', 'skinning'), ('fishing', 'fishing'), ('herbalism', 'herbalism'), ('mining', 'mining'), ('other', 'other'), ('drop', 'drop'), ('vendor', 'vendor'), ('poisons', 'poisons')], default='drop', max_length=15)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WoWClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Druid', 'Druid'), ('Hunter', 'Hunter'), ('Mage', 'Mage'), ('Paladin', 'Paladin'), ('Priest', 'Priest'), ('Rogue', 'Rogue'), ('Shaman', 'Shaman'), ('Warlock', 'Warlock'), ('Warrior', 'Warrior')], default='Warrior', max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TalentTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('position', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)])),
                ('wow_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.WoWClass')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('max_rank', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5)])),
                ('_description', models.CharField(max_length=400)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.TalentTree')),
                ('wow_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.WoWClass')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('creates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Crafted')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Item')),
            ],
        ),
        migrations.AddField(
            model_name='crafted',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Item'),
        ),
        migrations.AddField(
            model_name='crafted',
            name='materials',
            field=models.ManyToManyField(to='home.Material'),
        ),
    ]
