# Generated by Django 2.2.2 on 2019-06-13 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='formula',
            field=models.CharField(default='[x]', max_length=150),
        ),
        migrations.AddField(
            model_name='talent',
            name='x',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='talent',
            name='y',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7)]),
        ),
    ]
