# Generated by Django 2.2.4 on 2019-08-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumelist',
            name='queue',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spec',
            name='queue',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
