# Generated by Django 2.2.3 on 2019-07-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('pvp', 'PvP'), ('wpvp', 'wPvP'), ('bgs', 'BGs'), ('pve', 'PvE'), ('meme', 'MeMe'), ('mc', 'MC'), ('bwl', 'BWL'), ('zg', 'ZG'), ('aq20', 'AQ20'), ('aq40', 'AQ40'), ('naxx', 'Naxx'), ('5man', '5-man'), ('melee', 'Melee'), ('caster', 'Caster'), ('healer', 'Healer'), ('tank', 'Tank'), ('dps', 'DPS'), ('horde', 'Horde'), ('alliance', 'Alliance')], max_length=15, unique=True),
        ),
    ]
