# Generated by Django 2.2.3 on 2019-07-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190721_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talenttree',
            name='_architect',
            field=models.CharField(default='[]', max_length=2500),
        ),
    ]
