# Generated by Django 2.2.3 on 2019-08-08 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190803_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='img',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='talent',
            name='locked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Talent'),
        ),
    ]
