# Generated by Django 2.2.4 on 2019-08-23 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190823_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumelist',
            name='queue_type',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 for Specs, 1 for CLs', validators=[django.core.validators.MaxValueValidator(51)]),
        ),
        migrations.AddField(
            model_name='spec',
            name='queue_type',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 for Specs, 1 for CLs', validators=[django.core.validators.MaxValueValidator(51)]),
        ),
    ]
