# Generated by Django 2.2.3 on 2019-08-08 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190808_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='ix',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MaxValueValidator(8)]),
        ),
    ]
