# Generated by Django 2.2.3 on 2019-07-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190721_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talent',
            options={'ordering': ['id']},
        ),
    ]
