# Generated by Django 2.2.2 on 2019-06-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190613_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wowclass',
            name='name',
            field=models.CharField(choices=[('druid', 'druid'), ('hunter', 'hunter'), ('mage', 'mage'), ('paladin', 'paladin'), ('priest', 'priest'), ('rogue', 'rogue'), ('shaman', 'shaman'), ('warlock', 'warlock'), ('warrior', 'warrior')], default='Warrior', max_length=20, unique=True),
        ),
    ]
