# Generated by Django 2.2.4 on 2019-08-23 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190823_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumelist',
            name='img',
            field=models.CharField(default='samwise', max_length=30),
        ),
        migrations.AddField(
            model_name='spec',
            name='img',
            field=models.CharField(default='samwise', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='queue_type',
            field=models.PositiveSmallIntegerField(default=1, help_text='0 for Specs, 1 for CLs', validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
