# Generated by Django 2.2.2 on 2019-06-18 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_talenttree__architect'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='locked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Talent'),
        ),
        migrations.AlterUniqueTogether(
            name='talent',
            unique_together={('wow_class', 'name', 'tree')},
        ),
        migrations.AlterUniqueTogether(
            name='talenttree',
            unique_together={('wow_class', 'name')},
        ),
    ]
