# Generated by Django 2.2.3 on 2019-08-08 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190808_1442'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='setbonus',
            unique_together={('pieces', 'spell')},
        ),
    ]
