# Generated by Django 2.2.4 on 2019-08-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190823_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prevent_context_menu',
            field=models.BooleanField(default=True),
        ),
    ]
