# Generated by Django 2.2.2 on 2019-06-20 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(default='testy test', max_length=100)),
                ('name', models.CharField(default='', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Profile')),
                ('wow_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.WoWClass')),
            ],
        ),
    ]
