# Generated by Django 2.2.3 on 2019-08-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190808_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='school',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profession',
            name='img',
            field=models.CharField(max_length=40),
        ),
    ]
