# Generated by Django 2.2.2 on 2019-06-21 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_savedspec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='creates',
        ),
        migrations.RemoveField(
            model_name='material',
            name='item',
        ),
        migrations.DeleteModel(
            name='Crafted',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
