# Generated by Django 2.2.4 on 2019-08-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190824_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumelist',
            name='img',
            field=models.CharField(default='samwise', max_length=50),
        ),
        migrations.AlterField(
            model_name='consumelist',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='spec',
            name='img',
            field=models.CharField(default='samwise', max_length=50),
        ),
        migrations.AlterField(
            model_name='spec',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
