# Generated by Django 2.2.2 on 2019-06-21 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190621_1327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
