# Generated by Django 2.2.4 on 2020-07-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190824_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='equips',
            field=models.ManyToManyField(blank=True, related_name='equips', to='home.Spell'),
        ),
        migrations.AlterField(
            model_name='item',
            name='procs',
            field=models.ManyToManyField(blank=True, related_name='procs', to='home.Spell'),
        ),
        migrations.AlterField(
            model_name='item',
            name='proficiency',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='slot',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
