# Generated by Django 2.2.4 on 2020-07-02 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200702_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='armor',
            field=models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='damage',
            field=models.ManyToManyField(blank=True, to='home.Damage'),
        ),
        migrations.AlterField(
            model_name='item',
            name='speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)]),
        ),
    ]
