# Generated by Django 2.2.2 on 2019-06-21 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='required_level',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('gathered', 'gathered'), ('drop', 'drop'), ('quest', 'quest'), ('crafted', 'crafted'), ('vendor', 'vendor'), ('other', 'other')], default='drop', max_length=15),
        ),
    ]
