# Generated by Django 2.2.4 on 2020-07-02 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200702_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='_proficiency',
            field=models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='_slot',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Head'), (2, 'Neck'), (3, 'Shoulder'), (4, 'Shirt'), (5, 'Chest'), (6, 'Waist'), (7, 'Legs'), (8, 'Feet'), (9, 'Wrist'), (10, 'Hands'), (11, 'Finger'), (12, 'Finger2'), (13, 'Trinket'), (14, 'Trinket2'), (15, 'Back'), (16, 'Main Hand'), (17, 'Off Hand'), (18, 'Ranged'), (19, 'Tabard'), (20, 'Bag'), (21, 'Bag2'), (22, 'Bag3'), (23, 'Bag4'), (24, 'Two-hand'), (25, 'One-hand'), (26, 'Thrown'), (27, 'Relic'), (28, 'Held In Off-Hand'), (29, 'Projectile')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
