# Generated by Django 2.2.4 on 2020-07-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200702_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sidebar',
            field=models.BooleanField(default=True),
        ),
    ]
