# Generated by Django 2.2.2 on 2019-06-21 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190621_1509'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
