# Generated by Django 2.2.4 on 2020-07-23 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_user_sidebar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sidebar',
        ),
    ]
