# Generated by Django 2.2.3 on 2019-08-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190809_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumelist',
            name='hash',
        ),
    ]
