# Generated by Django 2.2.3 on 2019-08-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_consumelist_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumelist',
            name='hash',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='spec',
            name='hash',
            field=models.CharField(default='', max_length=100),
        ),
    ]
