# Generated by Django 2.2.2 on 2019-06-21 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
