# Generated by Django 2.2.2 on 2019-06-21 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rarity', models.CharField(choices=[('junk', 'junk'), ('common', 'common'), ('uncommon', 'uncommon'), ('rare', 'rare'), ('epic', 'epic'), ('legendary', 'legendary')], default='common', max_length=10)),
                ('unique', models.BooleanField(default=False)),
                ('bop', models.BooleanField(default=False)),
                ('use', models.CharField(blank=True, max_length=250)),
                ('proper_name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('category', models.CharField(choices=[('gathered', 'gathered'), ('drop', 'drop'), ('quest', 'quest'), ('crafted', 'crafted'), ('vendor', 'vendor'), ('other', 'other')], default='drop', max_length=15)),
                ('required_level', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(60)])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
