# Generated by Django 2.2.3 on 2019-08-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20190810_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talent',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='consumelist',
            name='hash',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
