# Generated by Django 2.2.2 on 2019-06-21 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crafted',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Item')),
                ('step', models.PositiveSmallIntegerField(default=1)),
            ],
            bases=('home.item',),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Item')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('creates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Crafted')),
            ],
            bases=('home.item',),
        ),
        migrations.AddField(
            model_name='crafted',
            name='materials',
            field=models.ManyToManyField(to='home.Material'),
        ),
        migrations.AddField(
            model_name='crafted',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Profession'),
        ),
    ]
