# Generated by Django 2.2.3 on 2019-08-13 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20190811_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='img',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='talent',
            name='locked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Talent'),
        ),
    ]
