# Generated by Django 2.2.2 on 2019-06-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20190621_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crafted',
            old_name='profession',
            new_name='prof',
        ),
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(choices=[('alchemy', 'alchemy'), ('blacksmithing', 'blacksmithing'), ('cooking', 'cooking'), ('enchanting', 'enchanting'), ('engineering', 'engineering'), ('leatherworking', 'leatherworking'), ('first_aid', 'first_aid'), ('skinning', 'skinning'), ('fishing', 'fishing'), ('herbalism', 'herbalism'), ('mining', 'mining')], default='alchemy', max_length=20, unique=True),
        ),
    ]
