# Generated by Django 2.2.2 on 2019-06-21 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20190621_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='creates',
        ),
        migrations.RemoveField(
            model_name='material',
            name='item_ptr',
        ),
        migrations.DeleteModel(
            name='Crafted',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
