# Generated by Django 2.2.4 on 2019-08-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20190813_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talenttree',
            options={'ordering': ['position'], 'verbose_name_plural': 'talent_trees'},
        ),
        migrations.AlterModelOptions(
            name='wowclass',
            options={'verbose_name_plural': 'classes'},
        ),
        migrations.AddField(
            model_name='user',
            name='max_lists',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
