# Generated by Django 2.2.4 on 2019-08-16 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20190815_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consume',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='consumelist',
            name='description',
            field=models.CharField(default='couple line of text...', max_length=2000),
        ),
        migrations.AlterField(
            model_name='spec',
            name='description',
            field=models.CharField(default='couple line of text...', max_length=2000),
        ),
        migrations.AlterField(
            model_name='user',
            name='max_lists',
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
