# Generated by Django 2.2.2 on 2019-06-21 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20190621_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crafted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveSmallIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('creates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Crafted')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Item')),
            ],
        ),
        migrations.AddField(
            model_name='crafted',
            name='materials',
            field=models.ManyToManyField(to='home.Material'),
        ),
        migrations.AddField(
            model_name='crafted',
            name='prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Profession'),
        ),
    ]
