# Generated by Django 2.2.2 on 2019-06-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20190621_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(blank=True, choices=[('alchemy', 'alchemy'), ('blacksmithing', 'blacksmithing'), ('cooking', 'cooking'), ('enchanting', 'enchanting'), ('engineering', 'engineering'), ('leatherworking', 'leatherworking'), ('first_aid', 'first_aid'), ('skinning', 'skinning'), ('fishing', 'fishing'), ('herbalism', 'herbalism'), ('mining', 'mining')], max_length=20, unique=True),
        ),
    ]
