# Generated by Django 2.2.4 on 2019-08-20 13:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20190816_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bagslots',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='crafted',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Profession'),
        ),
    ]
