# Generated by Django 2.2.2 on 2019-06-25 16:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20190621_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedspec',
            name='spent',
            field=models.ManyToManyField(to='home.Material'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(choices=[('alchemy', 'alchemy'), ('blacksmithing', 'blacksmithing'), ('cooking', 'cooking'), ('enchanting', 'enchanting'), ('engineering', 'engineering'), ('leatherworking', 'leatherworking'), ('first_aid', 'first_aid'), ('skinning', 'skinning'), ('fishing', 'fishing'), ('herbalism', 'herbalism'), ('mining', 'mining'), ('tailoring', 'tailoring')], default='alchemy', max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='savedspec',
            unique_together={('user', 'name')},
        ),
        migrations.CreateModel(
            name='TreeAllotted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invested', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(51)])),
                ('savedspec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.SavedSpec')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.TalentTree')),
            ],
            options={
                'unique_together': {('savedspec', 'tree')},
            },
        ),
    ]
