# Generated by Django 2.2.2 on 2019-06-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20190625_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedspec',
            name='spent',
        ),
    ]
