# Generated by Django 2.2.2 on 2019-06-26 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('home', '0026_remove_savedspec_spent'),
    ]
    operations = [
        migrations.RenameModel(
            old_name='SavedSpec',
            new_name='Spec',
        ),
        migrations.RenameField(
            model_name='treeallotted',
            old_name='savedspec',
            new_name='spec',
        ),
        migrations.AlterUniqueTogether(
            name='treeallotted',
            unique_together={('spec', 'tree')},
        ),
        migrations.CreateModel(
            name='ConsumeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Profile')),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
    ]
