# Generated by Django 2.2.2 on 2019-07-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20190626_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='spec',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('item', 'creates')},
        ),
    ]
