# Generated by Django 2.2.2 on 2019-07-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20190706_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spec',
            old_name='is_private',
            new_name='private',
        ),
        migrations.AddField(
            model_name='consumelist',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
