# Generated by Django 2.2.2 on 2019-07-06 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20190706_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='spec',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 7, 6, 17, 30, 26, 729345)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spec',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
