# Generated by Django 2.2.2 on 2019-07-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20190706_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumelist',
            name='description',
            field=models.TextField(default='couple line of text...', max_length=300),
        ),
        migrations.AddField(
            model_name='spec',
            name='description',
            field=models.TextField(default='couple line of text...', max_length=300),
        ),
    ]
