# Generated by Django 2.2.2 on 2019-07-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20190707_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('pvp', 'PvP'), ('wpvp', 'wPvP'), ('bgs', 'BGs'), ('pve', 'PvE'), ('meme', 'MeMe'), ('mc', 'MC'), ('bwl', 'BWL'), ('zg', 'ZG'), ('aq20', 'AQ20'), ('aq40', 'AQ40'), ('naxx', 'Naxx'), ('5man', '5-man')], max_length=5, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='spec',
            name='tags',
            field=models.ManyToManyField(related_name='spec_tags_related', related_query_name='spec_tags', to='home.Tag'),
        ),
    ]
