# Generated by Django 2.2.2 on 2019-07-08 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20190707_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumelist',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='consumelist',
            name='tags',
            field=models.ManyToManyField(related_name='consumelist_tags_related', related_query_name='consumelist_tags', to='home.Tag'),
        ),
        migrations.AddField(
            model_name='spec',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
