# Generated by Django 2.2.2 on 2019-07-09 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20190708_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumelist',
            name='consumes',
            field=models.ManyToManyField(to='home.Consume'),
        ),
        migrations.AddField(
            model_name='consumelist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 7, 9, 9, 7, 33, 905250)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumelist',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
