# Generated by Django 2.2.2 on 2019-07-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20190709_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='crafted',
            name='end_game',
            field=models.BooleanField(default=True),
        ),
    ]
