# Generated by Django 2.2.2 on 2019-07-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_crafted_end_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumelist',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='spec',
            name='rating',
        ),
        migrations.AlterField(
            model_name='crafted',
            name='end_game',
            field=models.BooleanField(default=False),
        ),
    ]
