# Generated by Django 2.2.2 on 2019-07-10 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consume',
            old_name='invested',
            new_name='amount',
        ),
    ]
