# Generated by Django 2.2.2 on 2019-07-11 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20190709_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consume',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
