# Generated by Django 2.2.2 on 2019-07-17 22:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20190711_0703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='item',
            name='image_name',
            field=models.CharField(default='images/icons/large/professions/other.jpg', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consume',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='consumelist',
            name='description',
            field=models.CharField(default='couple line of text...', max_length=1000),
        ),
        migrations.AlterField(
            model_name='spec',
            name='description',
            field=models.CharField(default='couple line of text...', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('pvp', 'PvP'), ('wpvp', 'wPvP'), ('bgs', 'BGs'), ('pve', 'PvE'), ('meme', 'MeMe'), ('mc', 'MC'), ('bwl', 'BWL'), ('zg', 'ZG'), ('aq20', 'AQ20'), ('aq40', 'AQ40'), ('naxx', 'Naxx'), ('5man', '5-man'), ('melee', 'Melee'), ('caster', 'Caster'), ('healer', 'Healer'), ('tank', 'Tank'), ('dps', 'DPS'), ('horde', 'Horde'), ('alliance', 'Alliance')], max_length=5, unique=True),
        ),
    ]
