# Generated by Django 2.2.3 on 2019-07-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20190717_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='rarity',
            new_name='quality',
        ),
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(choices=[('alchemy', 'alchemy'), ('blacksmithing', 'blacksmithing'), ('cooking', 'cooking'), ('enchanting', 'enchanting'), ('engineering', 'engineering'), ('leatherworking', 'leatherworking'), ('first_aid', 'first_aid'), ('skinning', 'skinning'), ('fishing', 'fishing'), ('herbalism', 'herbalism'), ('mining', 'mining'), ('tailoring', 'tailoring'), ('riding', 'riding')], default='alchemy', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='wowclass',
            name='name',
            field=models.CharField(choices=[('druid', 'druid'), ('hunter', 'hunter'), ('mage', 'mage'), ('paladin', 'paladin'), ('priest', 'priest'), ('rogue', 'rogue'), ('shaman', 'shaman'), ('warlock', 'warlock'), ('warrior', 'warrior')], default='warrior', max_length=20, unique=True),
        ),
    ]
