# Generated by Django 2.2.3 on 2019-07-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_auto_20190725_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='quality',
            new_name='rarity',
        ),
    ]
