# Generated by Django 2.2.3 on 2019-07-25 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20190725_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quality',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
